#!/usr/bin/env ruby

=begin
Copyright (C) 2018 Mark D. Blackwell.
   All rights reserved.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
=end

=begin
Delete comments, for Qplaylist Remember Songs Comments Process
=end

require_relative '../etc/methods_module_methods.rb'

module ::Command
  extend Methods

# Greet:
  greeting_at_opening

  filename = filename_command_ftp 'delete'

  confirm_ftp_command_file_exists filename

# Clear listener comments from the webserver computer:
  argument_ftp = "-s:#{filename}"
  command_run %w[ftp] + [argument_ftp]
end
