#!/usr/bin/env ruby

=begin
Copyright (C) 2018 Mark D. Blackwell.
   All rights reserved.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
=end

=begin
Set up, for Qplaylist Remember Songs Comments Process
=end

require_relative '../etc/methods'

module ::Command
  extend Methods

# Greet:
  greeting_at_opening

# Navigate to run Bundler:
  ::Dir.chdir project_root

# Install necessary gems:
## 'bundle install --without development test' is failing to exclude those dependencies:
##command_run %w[bundle install --without development test]
  command_run %w[bundle install]

  ::Kernel.exit child_status_integer unless command_ran_best

# Run the setup program:
  command_run %w[bundle exec ruby] + [filename_program_set_up]

  ::Kernel.exit child_status_integer unless command_ran_best
end
